import { useCallback, useEffect, useState } from "react";
import { fetchBankDetails, parseBankApiError, saveBankDetails } from "../api/bankapi";

const EMPTY = { accountHolderName: "", accountNumber: "", confirmAccountNumber: "", ifscCode: "", bankName: "", branchName: "", accountType: "", currentPassword: "", accountNumberLast4: "" };
const SAVED_FIELDS = ["accountHolderName", "ifscCode", "bankName", "branchName", "accountType", "accountNumberLast4"];
const ACCOUNT_TYPES = ["Savings", "Current"];
const inputBase = "h-[46px] rounded-md border bg-white px-2.5 text-sm text-gray-900 placeholder:text-gray-400 focus:border-amber-400 focus:outline-none focus:ring-4 focus:ring-amber-400/25";
const clean = (value) => String(value ?? "").trim().replace(/\s+/g, " ");

function validate(values) {
  const errors = {};
  if (clean(values.accountHolderName).length < 2 || clean(values.accountHolderName).length > 100) errors.accountHolderName = "Account holder name must be 2-100 characters.";
  if (!/^\d{9,18}$/.test(values.accountNumber)) errors.accountNumber = "Enter a valid account number (9-18 digits).";
  if (!values.confirmAccountNumber) errors.confirmAccountNumber = "Re-enter your account number.";
  else if (values.confirmAccountNumber !== values.accountNumber) errors.confirmAccountNumber = "Account numbers do not match.";
  if (!/^[A-Z]{4}0[A-Z0-9]{6}$/.test(values.ifscCode)) errors.ifscCode = "Enter a valid 11-character IFSC code.";
  if (clean(values.bankName).length < 2 || clean(values.bankName).length > 100) errors.bankName = "Bank name must be 2-100 characters.";
  if (clean(values.branchName).length < 2 || clean(values.branchName).length > 100) errors.branchName = "Branch name must be 2-100 characters.";
  if (!ACCOUNT_TYPES.includes(values.accountType)) errors.accountType = "Select an account type.";
  if (!values.currentPassword) errors.currentPassword = "Please confirm your password to update bank details.";
  return errors;
}

const toFormValues = (data) => ({ ...EMPTY, accountHolderName: data?.accountHolderName ?? "", ifscCode: data?.ifscCode ?? "", bankName: data?.bankName ?? "", branchName: data?.branchName ?? "", accountType: data?.accountType ?? "", accountNumberLast4: data?.accountNumberLast4 ?? "" });

export default function BankDetails() {
  const [saved, setSaved] = useState(EMPTY);
  const [values, setValues] = useState(EMPTY);
  const [errors, setErrors] = useState({});
  const [touched, setTouched] = useState({});
  const [loading, setLoading] = useState(true);
  const [loadFailed, setLoadFailed] = useState(false);
  const [saving, setSaving] = useState(false);
  const [banner, setBanner] = useState(null);
  const applyBank = useCallback((data) => { const next = toFormValues(data); setSaved(next); setValues(next); setErrors({}); setTouched({}); setLoadFailed(false); }, []);
  const loadBank = useCallback(async () => { setLoading(true); setLoadFailed(false); setBanner(null); try { applyBank(await fetchBankDetails()); } catch (err) { setLoadFailed(true); setBanner({ type: "error", text: parseBankApiError(err).message }); } finally { setLoading(false); } }, [applyBank]);
  useEffect(() => { let cancelled = false; (async () => { try { const data = await fetchBankDetails(); if (!cancelled) applyBank(data); } catch (err) { if (!cancelled) { setLoadFailed(true); setBanner({ type: "error", text: parseBankApiError(err).message }); } } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, [applyBank]);
  const dirty = SAVED_FIELDS.some((field) => values[field] !== saved[field]) || Boolean(values.accountNumber || values.confirmAccountNumber || values.currentPassword);
  const handleChange = (event) => { const { name, value } = event.target; let next = value; if (name === "accountNumber" || name === "confirmAccountNumber") next = value.replace(/\D/g, "").slice(0, 18); if (name === "ifscCode") next = value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 11); const form = { ...values, [name]: next }; setValues(form); setBanner(null); if (touched[name]) setErrors((previous) => ({ ...previous, [name]: validate(form)[name] })); };
  const handleBlur = (event) => { const { name } = event.target; setTouched((previous) => ({ ...previous, [name]: true })); setErrors((previous) => ({ ...previous, [name]: validate(values)[name] })); };
  const handleCancel = () => { setValues(saved); setErrors({}); setTouched({}); setBanner(null); };
  const handleSave = async () => { if (!dirty || saving) return; const found = validate(values); setErrors(found); if (Object.keys(found).length) { setTouched(Object.fromEntries(Object.keys(found).map((name) => [name, true]))); return; } setSaving(true); setBanner(null); try { applyBank(await saveBankDetails(values)); setBanner({ type: "success", text: "Bank details saved." }); } catch (err) { const { message, fieldErrors } = parseBankApiError(err); setErrors((previous) => ({ ...previous, ...fieldErrors })); setBanner({ type: "error", text: message }); } finally { setSaving(false); } };
  const renderField = ({ label, name, placeholder, maxLength, inputMode, options, onPaste, wide = false, type = "text", hint }) => { const error = errors[name]; const border = error ? "border-red-600" : "border-gray-300"; return <div className={`flex flex-col gap-1.5 ${wide ? "md:col-span-2" : ""}`}><label htmlFor={name} className="text-base text-gray-900">{label}</label>{options ? <select id={name} name={name} value={values[name]} onChange={handleChange} onBlur={handleBlur} aria-invalid={Boolean(error)} className={`${inputBase} ${border} ${values[name] ? "" : "text-gray-400"}`}><option value="" disabled>{placeholder}</option>{options.map((option) => <option key={option} value={option} className="text-gray-900">{option}</option>)}</select> : <input id={name} name={name} type={type} value={values[name]} onChange={handleChange} onBlur={handleBlur} onPaste={onPaste} placeholder={placeholder} maxLength={maxLength} inputMode={inputMode} autoComplete="off" aria-invalid={Boolean(error)} className={`${inputBase} ${border}`} />}{hint && <p className="m-0 text-xs text-gray-500">{hint}</p>}{error && <p className="m-0 text-xs text-red-600">{error}</p>}</div>; };
  if (loading) return <div className="flex max-w-[1100px] flex-col gap-6 pb-8 pt-2"><h1 className="m-0 text-[32px] font-bold text-gray-900">Bank Details</h1><p className="text-sm text-gray-500">Loading bank details…</p></div>;
  if (loadFailed) return <div className="flex max-w-[1100px] flex-col gap-6 pb-8 pt-2"><h1 className="m-0 text-[32px] font-bold text-gray-900">Bank Details</h1><p className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">{banner?.text || "Unable to load bank details."}</p><button type="button" onClick={loadBank} className="w-fit rounded border border-gray-900 bg-white px-4 py-2 text-sm font-semibold">Retry</button></div>;
  return <div className="flex max-w-[1100px] flex-col gap-6 pb-8 pt-2"><header><h1 className="m-0 text-[32px] font-bold text-gray-900">Bank Details</h1><p className="mb-0 mt-1.5 text-[15px] text-gray-800">Manage your bank account details for payouts.</p></header><section className="flex flex-col gap-4 rounded-[14px] border border-gray-200 bg-white px-3 pb-6 pt-4"><h2 className="m-0 text-[15px] font-bold text-gray-900">Account Information</h2>{values.accountNumberLast4 && <p className="m-0 text-sm text-gray-600">Saved account: •••• {values.accountNumberLast4}. Enter the full account number only to replace it.</p>}<div className="grid grid-cols-1 gap-x-4 gap-y-4 md:grid-cols-2">{renderField({ label: "Account Holder Name", name: "accountHolderName", placeholder: "Enter account holder name", maxLength: 100 })}{renderField({ label: "Account Number", name: "accountNumber", placeholder: "Enter account number to update", maxLength: 18, inputMode: "numeric" })}{renderField({ label: "Confirm Account Number", name: "confirmAccountNumber", placeholder: "Re-enter account number", maxLength: 18, inputMode: "numeric", onPaste: (event) => event.preventDefault() })}{renderField({ label: "IFSC Code", name: "ifscCode", placeholder: "Enter IFSC code", maxLength: 11 })}{renderField({ label: "Bank Name", name: "bankName", placeholder: "Enter bank name", maxLength: 100, wide: true })}{renderField({ label: "Branch Name", name: "branchName", placeholder: "Enter branch name", maxLength: 100 })}{renderField({ label: "Account Type", name: "accountType", placeholder: "Select account type", options: ACCOUNT_TYPES })}{renderField({ label: "Current Password", name: "currentPassword", placeholder: "Confirm password to save changes", type: "password", wide: true })}</div></section>{banner && <p className={`m-0 rounded-md px-3 py-2 text-sm ${banner.type === "success" ? "border border-green-200 bg-green-50 text-green-800" : "border border-red-200 bg-red-50 text-red-700"}`} role={banner.type === "error" ? "alert" : "status"}>{banner.text}</p>}<div className="flex flex-col-reverse gap-5 md:flex-row md:justify-end"><button type="button" onClick={handleCancel} disabled={!dirty || saving} className="h-12 w-full cursor-pointer rounded border border-gray-900 bg-white text-lg font-semibold disabled:opacity-60 md:h-[54px] md:w-[220px]">Cancel</button><button type="button" onClick={handleSave} disabled={!dirty || saving} className="h-12 w-full cursor-pointer rounded border border-green-700 bg-green-700 text-lg font-semibold text-white disabled:opacity-60 md:h-[54px] md:w-[220px]">{saving ? "Saving..." : "Save"}</button></div></div>;
}
